### PR TITLE
Add correct dependencys so the Alpine images can build RocksDB 5.9.0

### PR DESCRIPTION
**Pull request by double16**

### CODE REVIEW

**Review by adamretter — COMMENTED** [review]
So we still need Glibc? Or will there be a separate PR for rocksjava with music?

**Comment by adamretter** [comment]
Damn autocorrect. I mean "muslc" not "music"!

**Comment by double16** [comment]
Do you mean the alpine-glibc image? I don't see why it's needed since the centos images build the glibc versions.

The rocksjava PR will be updated shortly.

**Comment by adamretter** [comment]
Sorry in your PR you still have this line:

> # install GCC and build tools

Not sure if it is intentional or not?

**Review by adamretter — COMMENTED** [review]
Ah ha!

**Pull request merged**
